spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kingcrab
    username: root
    password: dlagkstjd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect